name: ci
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm run install

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run : npm run build
